language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

cache:
   directories:
     - $HOME/.composer/cache

install: travis_retry composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit

notifications:
    email: false
